
C:\Users\safiz\Reposites\Learn_git>dir
 Volume in drive C is Windows
 Volume Serial Number is 046C-22DD

 Directory of C:\Users\safiz\Reposites\Learn_git

21-02-2025  08:40    <DIR>          .
21-02-2025  08:39    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  148,870,021,120 bytes free

C:\Users\safiz\Reposites\Learn_git>dir /A 
 Volume in drive C is Windows
 Volume Serial Number is 046C-22DD

 Directory of C:\Users\safiz\Reposites\Learn_git

21-02-2025  08:40    <DIR>          .
21-02-2025  08:39    <DIR>          ..
21-02-2025  08:42    <DIR>          .git
               0 File(s)              0 bytes
               3 Dir(s)  148,870,021,120 bytes free

C:\Users\safiz\Reposites\Learn_git>python learn.py
5
0 1 2 3 4 
C:\Users\safiz\Reposites\Learn_git>python learn.py
5
1 2 3 4 5 
C:\Users\safiz\Reposites\Learn_git>git add .

C:\Users\safiz\Reposites\Learn_git>git commit -m "I have created a py file to print numbers"
[master (root-commit) 205c6b7] I have created a py file to print numbers
 1 file changed, 6 insertions(+)
 create mode 100644 learn.py

C:\Users\safiz\Reposites\Learn_git>git status
On branch master
nothing to commit, working tree clean

C:\Users\safiz\Reposites\Learn_git>git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   learn.py

no changes added to commit (use "git add" and/or "git commit -a")

C:\Users\safiz\Reposites\Learn_git>git restore learn.py

C:\Users\safiz\Reposites\Learn_git>git status
On branch master
nothing to commit, working tree clean

C:\Users\safiz\Reposites\Learn_git>git log
commit 205c6b7123ewwdfr43wsdfgt43wsdfra9367e16b167db4c35f88 (HEAD -> master)
Author: Safaizal <3434243+Safaizal@users.noreply.github.com>
Date:   Fri Feb 21 08:46:28 2025 +0530

    I have created a py file to print numbers

C:\Users\safiz\Reposites\Learn_git>git remote origin 

C:\Users\safiz\Reposites\Learn_git>git remote add origin https://github.com/Safaizal/Learn_git.git

C:\Users\safiz\Reposites\Learn_git>git remote -v
origin  https://github.com/Safaizal/Learn_git.git (fetch)
origin  https://github.com/Safaizal/Learn_git.git (push)

C:\Users\safiz\Reposites\Learn_git>git push origin master
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 4 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 324 bytes | 81.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
To https://github.com/Safaizal/Learn_git.git
 * [new branch]      master -> master

C:\Users\safiz\Reposites\Learn_git>git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        laptop.py

nothing added to commit but untracked files present (use "git add" to track)

C:\Users\safiz\Reposites\Learn_git>git stash
No local changes to save

C:\Users\safiz\Reposites\Learn_git>git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        laptop.py

nothing added to commit but untracked files present (use "git add" to track)

C:\Users\safiz\Reposites\Learn_git>git stash laptop.py
fatal: subcommand wasn't specified; 'push' can't be assumed due to unexpected token 'laptop.py'

C:\Users\safiz\Reposites\Learn_git>git add .

C:\Users\safiz\Reposites\Learn_git>git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   laptop.py


C:\Users\safiz\Reposites\Learn_git>git stash
Saved working directory and index state WIP on master: 205c6b7 I have created a py file to print numbers

C:\Users\safiz\Reposites\Learn_git>git stash pop
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   laptop.py

Dropped refs/stash@{0} (11665a662342342420168d2acadb3d30b23fb)

C:\Users\safiz\Reposites\Learn_git>git commit -m "i have added file named laptop"
[master 42f8d64] i have added file named laptop
 1 file changed, 1 insertion(+)
 create mode 100644 laptop.py

C:\Users\safiz\Reposites\Learn_git>git log
commit 42f8d64557dea234v234v322806469643d2fce30 (HEAD -> master)
Author: Safaizal <23423424+Safaizal@users.noreply.github.com>
Date:   Fri Feb 21 08:58:29 2025 +0530

    i have added file named laptop

commit 205c6b7a92c2fr34r3453re16b167db4c35f88 (origin/master)
Author: Safaizal <342323+Safaizal@users.noreply.github.com>
Date:   Fri Feb 21 08:46:28 2025 +0530

    I have created a py file to print numbers

C:\Users\safiz\Reposites\Learn_git>git branch main

C:\Users\safiz\Reposites\Learn_git>git checkout main
Switched to branch 'main'

C:\Users\safiz\Reposites\Learn_git>git push origin main
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 4 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 340 bytes | 113.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
remote: 
remote: Create a pull request for 'main' on GitHub by visiting:
remote:      https://github.com/Safaizal/Learn_git/pull/new/main
remote:
To https://github.com/Safaizal/Learn_git.git
 * [new branch]      main -> main

C:\Users\safiz\Reposites\Learn_git>git log
commit 42f8d6235252v523cdx50f806469643d2fce30 (HEAD -> main, origin/main, master)
Author: Safaizal <122352v18+Safaizal@users.noreply.github.com>
Date:   Fri Feb 21 08:58:29 2025 +0530

    i have added file named laptop

commit 205c35v23cdcvb29367e16b167db4c35f88 (origin/master)
Author: Safaizal <235234523+Safaizal@users.noreply.github.com>
Date:   Fri Feb 21 08:46:28 2025 +0530

    I have created a py file to print numbers

C:\Users\safiz\Reposites\Learn_git>git merge main     
Already up to date.

C:\Users\safiz\Reposites\Learn_git>git checkout master
Switched to branch 'master'

C:\Users\safiz\Reposites\Learn_git>git add .

C:\Users\safiz\Reposites\Learn_git>git commit -m "Successfully created and merged the branchs main and master by pull request" 
[master b5cd931] Successfully created and merged the branchs main and master by pull request
 1 file changed, 3 insertions(+), 1 deletion(-)

C:\Users\safiz\Reposites\Learn_git>git push origin master
To https://github.com/Safaizal/Learn_git.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/Safaizal/Learn_git.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

C:\Users\safiz\Reposites\Learn_git>git push origin main  
Everything up-to-date

C:\Users\safiz\Reposites\Learn_git>git remote -v
origin  https://github.com/Safaizal/Learn_git.git (fetch)
origin  https://github.com/Safaizal/Learn_git.git (push)

C:\Users\safiz\Reposites\Learn_git>git log
commit b5cd9234v23c3cfdxd234aefaa926e31da6e21af47d8 (HEAD -> master)
Author: Safaizal <4234234+Safaizal@users.noreply.github.com>
Date:   Fri Feb 21 09:11:00 2025 +0530

    Successfully created and merged the branchs main and master by pull request

commit 42f8d6v2c3f54f23fc06469643d2fce30 (origin/main, main)
Author: Safaizal <4234+Safaizal@users.noreply.github.com>
Date:   Fri Feb 21 08:58:29 2025 +0530

    i have added file named laptop

commit 205c6b7a92c2f02c3c3f4242e16b167db4c35f88 (origin/master)
Author: Safaizal <34234+Safaizal@users.noreply.github.com>
Date:   Fri Feb 21 08:46:28 2025 +0530

    I have created a py file to print numbers

C:\Users\safiz\Reposites\Learn_git>git branch master
fatal: a branch named 'master' already exists

C:\Users\safiz\Reposites\Learn_git>git push --delete origin main
To https://github.com/Safaizal/Learn_git.git
 - [deleted]         main

C:\Users\safiz\Reposites\Learn_git>git add .

C:\Users\safiz\Reposites\Learn_git>git commit -m "Successfully deleted the main branch after merged to the master branch"
On branch master
nothing to commit, working tree clean

C:\Users\safiz\Reposites\Learn_git>git push origin master
To https://github.com/Safaizal/Learn_git.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/Safaizal/Learn_git.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

C:\Users\safiz\Reposites\Learn_git>git fetch origin master
fatal: unable to access 'https://github.com/Safaizal/Learn_git.git/': Failed to connect to github.com port 443 after 21092 ms: Could not connect to server

C:\Users\safiz\Reposites\Learn_git>git remote-v
git: 'remote-v' is not a git command. See 'git --help'.

The most similar command is
        remote-fd

C:\Users\safiz\Reposites\Learn_git>git remote -v
origin  https://github.com/Safaizal/Learn_git.git (fetch)
origin  https://github.com/Safaizal/Learn_git.git (push)

C:\Users\safiz\Reposites\Learn_git>git push origin main   
Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 4 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (6/6), 632 bytes | 63.00 KiB/s, done.
Total 6 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
remote: 
remote: Create a pull request for 'main' on GitHub by visiting:
remote:      https://github.com/Safaizal/Learn_git/pull/new/main
remote:
To https://github.com/Safaizal/Learn_git.git
 * [new branch]      main -> main

C:\Users\safiz\Reposites\Learn_git>git branch
  main
* master

C:\Users\safiz\Reposites\Learn_git>git checkout main                  
Switched to branch 'main'

C:\Users\safiz\Reposites\Learn_git>git push --set-upstream origin main:master
To https://github.com/Safaizal/Learn_git.git
 ! [rejected]        main -> master (fetch first)
error: failed to push some refs to 'https://github.com/Safaizal/Learn_git.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

C:\Users\safiz\Reposites\Learn_git>git checkout master
Switched to branch 'master'

* master

C:\Users\safiz\Reposites\Learn_git>git checkout main
Switched to branch 'main'

C:\Users\safiz\Reposites\Learn_git>git push --set-upstream origin main:master
To https://github.com/Safaizal/Learn_git.git
 ! [rejected]        main -> master (fetch first)
error: failed to push some refs to 'https://github.com/Safaizal/Learn_git.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

C:\Users\safiz\Reposites\Learn_git>git checkout master
Switched to branch 'master'

C:\Users\safiz\Reposites\Learn_git>git push --set-upstream origin main:master
To https://github.com/Safaizal/Learn_git.git
 ! [rejected]        main -> master (fetch first)
error: failed to push some refs to 'https://github.com/Safaizal/Learn_git.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

C:\Users\safiz\Reposites\Learn_git>git checkout master
Switched to branch 'master'

 ! [rejected]        main -> master (fetch first)
error: failed to push some refs to 'https://github.com/Safaizal/Learn_git.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

C:\Users\safiz\Reposites\Learn_git>git checkout master
Switched to branch 'master'

hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

C:\Users\safiz\Reposites\Learn_git>git checkout master
Switched to branch 'master'

C:\Users\safiz\Reposites\Learn_git>git checkout master
Switched to branch 'master'

Switched to branch 'master'

C:\Users\safiz\Reposites\Learn_git>git pull origin master

C:\Users\safiz\Reposites\Learn_git>git pull origin master
C:\Users\safiz\Reposites\Learn_git>git pull origin master
fatal: unable to access 'https://github.com/Safaizal/Learn_git.git/': Failed to connect to github.com port 443 after 21102 ms: Could not connect to server

C:\Users\safiz\Reposites\Learn_git>git push --help

C:\Users\safiz\Reposites\Learn_git>git push --help

C:\Users\safiz\Reposites\Learn_git>git push --help


C:\Users\safiz\Reposites\Learn_git>git add .
C:\Users\safiz\Reposites\Learn_git>git add .

C:\Users\safiz\Reposites\Learn_git>git add .

C:\Users\safiz\Reposites\Learn_git>git commit -m "I have added the Learn_git.txt which of my terminal" 
[master dfef44d] I have added the Learn_git.txt which of my terminal
 1 file changed, 289 insertions(+)
 create mode 100644 Learn_git.txt

C:\Users\safiz\Reposites\Learn_git>git push origin main
Everything up-to-date

C:\Users\safiz\Reposites\Learn_git>git merge main
Already up to date.

C:\Users\safiz\Reposites\Learn_git>git status
On branch master
nothing to commit, working tree clean

C:\Users\safiz\Reposites\Learn_git>git log
commit dfef44d861d248f38fc4fd61641821de5a86eb921 (HEAD -> master)
Author: Safaizal <127269918+Safaizal@users.noreply.github.com>
Date:   Fri Feb 21 09:35:12 2025 +0530

    I have added the Learn_git.txt which of my terminal

commit b5cd931881dsdfdb6a38aefaa926e31da6e21af47d8
Author: Safaizal <127269918+Safaizal@users.noreply.github.com>
Date:   Fri Feb 21 09:11:00 2025 +0530

    Successfully created and merged the branchs main and master by pull request

commit 42f8d64d557ddea3bca0f6950f806469643d2fce30 (origin/main, main)
Author: Safaizal <127269918+Safaizal@users.noreply.github.com>
Date:   Fri Feb 21 08:58:29 2025 +0530

    i have added file named laptop

commit 205c6b7a92c2f07f98b8a9367e16b167db4c35f88 (origin/master)
Author: Safaizal <127269918+Safaizal@users.noreply.github.com>
Date:   Fri Feb 21 08:46:28 2025 +0530

    I have created a py file to print numbers

C:\Users\safiz\Reposites\Learn_git>git reset 205c6b7a92c2f0798b8a9367e16b167db4c35f88

C:\Users\safiz\Reposites\Learn_git>git remote -v
origin  https://github.com/Safaizal/Learn_git.git (fetch)
origin  https://github.com/Safaizal/Learn_git.git (push)

C:\Users\safiz\Reposites\Learn_git>git branch
  main
* master

C:\Users\safiz\Reposites\Learn_git>git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        Learn_git.txt
        laptop.py

nothing added to commit but untracked files present (use "git add" to track)

C:\Users\safiz\Reposites\Learn_git>git add .

C:\Users\safiz\Reposites\Learn_git>git commit -m "I have reseted the log by git reset"
[master 8ba948b] I have reseted the log by git reset
 2 files changed, 292 insertions(+)
 create mode 100644 Learn_git.txt
 create mode 100644 laptop.py

C:\Users\safiz\Reposites\Learn_git>git push origin master
To https://github.com/Safaizal/Learn_git.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/Safaizal/Learn_git.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

C:\Users\safiz\Reposites\Learn_git>git fetch origin
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (1/1), 901 bytes | 150.00 KiB/s, done.
From https://github.com/Safaizal/Learn_git
   205c6b7..a35eb5c  master     -> origin/master

C:\Users\safiz\Reposites\Learn_git>git pull origin master --rebase
From https://github.com/Safaizal/Learn_git
 * branch            master     -> FETCH_HEAD
Auto-merging laptop.py
CONFLICT (add/add): Merge conflict in laptop.py
error: could not apply 8ba948b... I have reseted the log by git reset
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config advice.mergeConflict false"
Could not apply 8ba948b... I have reseted the log by git reset

C:\Users\safiz\Reposites\Learn_git>git fetch origin

C:\Users\safiz\Reposites\Learn_git>git reset 205c6b7a92c2f0d79fdb8a9367e16b167db4c35f88

C:\Users\safiz\Reposites\Learn_git>git stash
No local changes to save

C:\Users\safiz\Reposites\Learn_git>git add .

C:\Users\safiz\Reposites\Learn_git>git stash
Saved working directory and index state WIP on (no branch): 205c6b7 I have created a py file to print numbers

C:\Users\safiz\Reposites\Learn_git>git stash clear

C:\Users\safiz\Reposites\Learn_git>git stash pop
No stash entries found.

C:\Users\safiz\Reposites\Learn_git>git add .

C:\Users\safiz\Reposites\Learn_git>git commit -m "Testing"
interactive rebase in progress; onto a35eb5c
Last command done (1 command done):
   pick 8ba948b I have reseted the log by git reset
No commands remaining.
You are currently editing a commit while rebasing branch 'master' on 'a35eb5c'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

nothing to commit, working tree clean

C:\Users\safiz\Reposites\Learn_git>git rebase --continue
Successfully rebased and updated refs/heads/master.

C:\Users\safiz\Reposites\Learn_git>git commit -m "Testing"
On branch master
nothing to commit, working tree clean

C:\Users\safiz\Reposites\Learn_git>git push origin master
To https://github.com/Safaizal/Learn_git.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/Safaizal/Learn_git.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

C:\Users\safiz\Reposites\Learn_git>git checkout master
Already on 'master'

C:\Users\safiz\Reposites\Learn_git>git branch 
  main
* master

C:\Users\safiz\Reposites\Learn_git>git push --delete origin main
fatal: unable to access 'https://github.com/Safaizal/Learn_git.git/': Failed to connect to github.com port 443 after 21782 ms: Could not connect to server

C:\Users\safiz\Reposites\Learn_git>git remote -v
origin  https://github.com/Safaizal/Learn_git.git (fetch)
origin  https://github.com/Safaizal/Learn_git.git (push)

C:\Users\safiz\Reposites\Learn_git>git log
commit 205c6b7a92c2f0798b8a9367e16b167db4c35f88 (HEAD -> master)
Author: Safaizal <127269918+Safaizal@users.noreply.github.com>
Date:   Fri Feb 21 08:46:28 2025 +0530

    I have created a py file to print numbers

C:\Users\safiz\Reposites\Learn_git>git add .

C:\Users\safiz\Reposites\Learn_git>git push origin master
To https://github.com/Safaizal/Learn_git.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/Safaizal/Learn_git.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

C:\Users\safiz\Reposites\Learn_git>git pul master
git: 'pul' is not a git command. See 'git --help'.

The most similar commands are
        pull
        push

C:\Users\safiz\Reposites\Learn_git>git pull master
fatal: 'master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

C:\Users\safiz\Reposites\Learn_git>git pull origin master
From https://github.com/Safaizal/Learn_git
 * branch            master     -> FETCH_HEAD
Updating 205c6b7..a35eb5c
Fast-forward
 laptop.py | 1 +
 1 file changed, 1 insertion(+)
 create mode 100644 laptop.py

C:\Users\safiz\Reposites\Learn_git>git push origin master
fatal: unable to access 'https://github.com/Safaizal/Learn_git.git/': Failed to connect to github.com port 443 after 21119 ms: Could not connect to server

C:\Users\safiz\Reposites\Learn_git>ping github.com

Pinging github.com [20.207.73.82] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 20.207.73.82:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

C:\Users\safiz\Reposites\Learn_git>git push origin master
Everything up-to-date
